spring.datasource.url=${XATA_DB}
spring.datasource.username=${WORKSPACE_ID}
spring.datasource.password=${API_KEY}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================
# Logging Configuration
# =========================

# Root logging level (applies to everything)
logging.level.root=INFO

# Spring framework internal logs (make it less noisy)
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# Your application package (detailed logs for your code)
logging.level.com.mzwiliapp=DEBUG

# Log pattern (console output format)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Optionally write logs to a file
logging.file.name=logs/app.log
logging.file.path=./logs
